import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import clsx from "clsx";
import NextTopLoader from "nextjs-toploader";
import { Space_Grotesk } from "next/font/google";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx("font-sans antialiased", spaceGrotesk.className)}>
        <NextTopLoader />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
