import {
  BarChart,
  Bell,
  Calendar,
  Clipboard,
  CreditCard,
  Database,
  FileCheck,
  FileText,
  Folder,
  Home,
  Info,
  Printer,
  Server,
  Settings,
  ShieldCheck,
  User,
  Users,
} from "lucide-react";

export const icons = [
  { name: "Home", component: <Home size={20} /> },
  { name: "Settings", component: <Settings size={20} /> },
  { name: "User", component: <User size={20} /> },
  { name: "CreditCard", component: <CreditCard size={20} /> },
  { name: "FileText", component: <FileText size={20} /> },
  { name: "Clipboard", component: <Clipboard size={20} /> },
  { name: "BarChart", component: <BarChart size={20} /> },
  { name: "Users", component: <Users size={20} /> },
  { name: "Calendar", component: <Calendar size={20} /> },
  { name: "Printer", component: <Printer size={20} /> },
  { name: "FileCheck", component: <FileCheck size={20} /> },
  { name: "Bell", component: <Bell size={20} /> },
  { name: "Database", component: <Database size={20} /> },
  { name: "Server", component: <Server size={20} /> },
  { name: "ShieldCheck", component: <ShieldCheck size={20} /> },
  { name: "Info", component: <Info size={20} /> },
  { name: "Folder", component: <Folder size={20} /> },
];
